Melao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # Importa settings
from django.conf.urls.static import static # Importa static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('melaoapp.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

melaoapp/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import views as auth_views

app_name = 'melaoapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('chats/', views.chat_list_view, name='chat_list_view'),
    path('chat/', views.chat_view, name='chat_view'),
    path('friends/', views.friends_list, name='friends_list'),
    path('config/language-theme/', views.language_and_theme_config_view, name='language_and_theme_config_view'),
    path('config/about-me/', views.about_me_config_view, name='about_me_config_view'),
    path('config/password-change', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('config/notifications', views.notifications_config_view, name='notifications_config'),
    path('config/privacy', views.privacy_config_view, name='privacy_config'),
    path('profile/edit/', views.modify_profile, name='modify_profile'),
    path('new-post/', views.new_post_view, name='new_post_view'),
    path('post/', views.post_view, name='post_view'),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search_person_view, name='search_person_view'),
    path('signup/', views.sign_up_view, name='sign_up_view'),
    path('notifications/', views.view_notifications, name='view_notifications'),
    path('', views.welcome, name='welcome'),
    path('welcome/', views.welcome, name='welcome-root'),
    path('set-theme/', views.set_theme, name='set_theme'),
    path('search/send-notification/', views.send_notification, name='send-notification'),
    path('notifications/accept-friend-request/', views.accept_friend_request, name='accept-friend-request'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="melaoapp/password_reset.html", email_template_name='melaoapp/password_reset_email.html', success_url='/reset_password_sent/' ), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="melaoapp/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="melaoapp/password_reset_confirm.html", success_url='/reset_password_complete/'), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="melaoapp/password_reset_complete.html"), name="password_reset_complete"),
]

melaoapp/forms.py
# melaoapp/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Student, Post
from django.db import transaction

class CustomUserCreationForm(UserCreationForm):
    # Campos adicionales para el registro
    email = forms.EmailField(required=True, help_text='Requerido.')
    first_name = forms.CharField(max_length=150, required=True, label="Nombre")
    last_name = forms.CharField(max_length=150, required=True, label="Apellido")
    date_of_birth = forms.DateField(
        required=True,
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Fecha de Nacimiento"
    )
    gender = forms.ChoiceField(
        choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')],
        required=False,
        label="Género"
    )

    class Meta(UserCreationForm.Meta):
        model = User
        # Se especifican solo los campos que pertenecen al modelo User y los que maneja el formulario base.
        # Los campos extra (date_of_birth, gender) se manejan en el método save.
        fields = ("username", "email", "first_name", "last_name")

    @transaction.atomic
    def save(self, commit=True):
        # El método save ahora se encarga de crear el User y el Student de forma segura.
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        
        if commit:
            user.save()
            # Se crea el objeto Student asociado al usuario recién creado
            Student.objects.create(
                user=user,
                date_of_birth=self.cleaned_data['date_of_birth'],
                gender=self.cleaned_data.get('gender'),
            )
        return user

class StudentSelfDescriptionForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['self_description']

class PrivacySettingsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['private_profile']
        
class NotificationsSettingsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['email_notifications']

class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['profile_picture']

class PostForm(forms.ModelForm):
    privacy_settings = forms.IntegerField(
        widget=forms.HiddenInput(),
        initial=1
    )
    class Meta:
        model = Post
        fields = ['description', 'multimedia', 'privacy_settings']
        widgets = {
            'description': forms.Textarea(attrs={
                'placeholder': 'Escribe lo que estás pensando...',
                'class': 'text-area-custom',
                'rows': 4
            }),
            'multimedia': forms.FileInput(attrs={
                'class': 'visually-hidden',
                'accept': 'image/*,video/*'
            }),
        }

melaoapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm, PostForm, PrivacySettingsForm, NotificationsSettingsForm, StudentSelfDescriptionForm, ProfilePictureForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Is_friend_of, Post, Student, Notification
from .forms import StudentSelfDescriptionForm
from django.http import JsonResponse
from django.utils import timezone
import json
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from datetime import date
from django.contrib.auth import logout


@login_required(login_url='melaoapp:welcome')
def chat_list_view(request):
    return render(request, 'melaoapp/chatListView.html')

@login_required(login_url='melaoapp:welcome')
def friends_list(request):
    current_student = Student.objects.get(user=request.user)
    
    friendships = Is_friend_of.objects.filter(Q(username_1=current_student))
    
    friends = []
    for friendship in friendships:
        if friendship.username_1 == current_student:
            friends.append(friendship.username_2)
            
    context = {'friends': friends}
    return render(request, 'melaoapp/friendsList.html', context)

@login_required(login_url='melaoapp:welcome')
def language_and_theme_config_view(request):
    return render(request, 'melaoapp/languageAndThemeConfigView.html')

@login_required(login_url='melaoapp:welcome')
def modify_profile(request):
    student = request.user.student
    if request.method == "POST":
        form = ProfilePictureForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('melaoapp:modify_profile')
    else:
        form = ProfilePictureForm(instance=student)
    return render(request, 'melaoapp/modifyProfile.html', {'form': form})

@login_required(login_url='melaoapp:welcome')
def profile(request):
    full_name = request.user.get_full_name()
    self_description = request.user.student.self_description
    posts = Post.objects.filter(username=request.user.student).order_by('-post_date')
    context = {"full_name": full_name, "self_description": self_description, "posts":posts}
    return render(request, 'melaoapp/profile.html', context)

@login_required(login_url='melaoapp:welcome')
def search_person_view(request):
    persons = Student.objects.select_related('user').exclude(user=request.user)
    context = {'persons': persons}
    return render(request, 'melaoapp/searchPersonView.html', context)
  
@login_required(login_url='melaoapp:welcome')
def send_notification(request):
    if request.method == 'POST':
        try:
            body_unicode = request.body.decode('utf-8')
            body_data = json.loads(body_unicode)

            recipient_username = body_data.get('recipient_username')
            sender_username = body_data.get('sender_username')
            notification_type = body_data.get('type')

            if not recipient_username or not sender_username or not notification_type:
                return JsonResponse({'status': 'error', 'message': 'Datos incompletos.'}, status=400)

            sender_student = Student.objects.get(user__username=sender_username)
            recipient_student = Student.objects.get(user__username=recipient_username)

            notification = Notification(
                sender_username=sender_student,
                sending_date=timezone.now(),
                type=notification_type,
                receiver_username=recipient_student
            )

            notification.save()
            
            return JsonResponse({'status': 'success'})

        except Student.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'El remitente o destinatario no existe.'}, status=404)
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Formato JSON inválido.'}, status=400)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': f'Ocurrió un error inesperado: {str(e)}'}, status=500)
    
    return JsonResponse({'status': 'error', 'message': 'Método no permitido.'}, status=405)

@login_required(login_url='melaoapp:welcome')
def accept_friend_request(request):
    try:
        body_unicode = request.body.decode('utf-8')
        body_data = json.loads(body_unicode)
        
        sender_username_str = body_data.get('sender')

        if not sender_username_str:
            return JsonResponse({'status': 'error', 'message': 'Datos de usuario incompletos.'}, status=400)
        
        current_student = Student.objects.get(user=request.user)
        
        try:
            sender_student = Student.objects.get(user__username=sender_username_str)
        except Student.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'El usuario que envía la solicitud no existe.'}, status=404)

        Is_friend_of.objects.create(
            username_1=sender_student,
            username_2=current_student
        )
        
        Is_friend_of.objects.create(
            username_1=current_student,
            username_2=sender_student
        )

        return JsonResponse({'status': 'success', 'message': 'Amistad aceptada con éxito.'})

    except json.JSONDecodeError:
        return JsonResponse({'status': 'error', 'message': 'Formato JSON inválido.'}, status=400)
    
    except Student.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'El usuario actual no existe como estudiante.'}, status=404)
    
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'Ha ocurrido un error: {str(e)}'}, status=500)

@login_required(login_url='melaoapp:welcome')
def view_notifications(request):
    current_student = Student.objects.get(user=request.user)

    notifications = Notification.objects.filter(receiver_username=current_student)

    context = {
        'notifications': notifications
    }

    return render(request, 'melaoapp/viewNotifications.html', context)

@login_required(login_url='melaoapp:welcome')
def home(request):
    try:
        current_student = Student.objects.get(user=request.user)
    except Student.DoesNotExist:
        return render(request, 'melaoapp/home.html', {'posts': []})

    friendships = Is_friend_of.objects.filter(
        Q(username_1=current_student) | Q(username_2=current_student)
    )

    friend_ids = []
    for friendship in friendships:
        if friendship.username_1 == current_student:
            friend_ids.append(friendship.username_2.id)
        else:
            friend_ids.append(friendship.username_1.id)

    posts = Post.objects.filter(
        username_id__in=friend_ids
    ).select_related(
        'username__user'
    ).order_by(
        '-post_date'
    )[:100]
    return render(request, 'melaoapp/home.html', {'posts': posts})

@login_required(login_url='melaoapp:welcome')
def chat_view(request):
    return render(request, 'melaoapp/chatView.html')

@login_required(login_url='melaoapp:welcome')
def post_view(request):
    return render(request, 'melaoapp/postView.html')

def sign_up_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('melaoapp:welcome')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'melaoapp/signUpView.html', {'form': form})

def welcome(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('melaoapp:home')
    else:
        form = AuthenticationForm()
    
    return render(request, 'melaoapp/welcome.html', {'form': form})

def set_theme(request):
    if request.method == 'GET':
        theme = request.GET.get('theme', 'light')
        if theme not in ['light', 'dark']:
            theme = 'light'
        response = redirect(request.META.get('HTTP_REFERER', '/')) 
        response.set_cookie('theme', theme, max_age=60*60*24*365)
        return response
    return redirect('/')

@login_required
def about_me_config_view(request):
    student = Student.objects.get(user=request.user)
    if request.method == "POST":
        form = StudentSelfDescriptionForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('melaoapp:profile')
    else:
        form = StudentSelfDescriptionForm(instance=student)
    return render(request, 'melaoapp/aboutMeConfigView.html', {'form': form})

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'melaoapp/passwordChangeView.html'
    success_url = reverse_lazy('melaoapp:modify_profile')

@login_required
def privacy_config_view(request):
    student = Student.objects.get(user=request.user)
    if request.method == "POST":
        form = PrivacySettingsForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('melaoapp:privacy_config')
    else:
        form = PrivacySettingsForm(instance=student)
    return render(request, 'melaoapp/privacyConfigView.html', {'form': form})

@login_required
def notifications_config_view(request):
    student = Student.objects.get(user=request.user)
    if request.method == "POST":
        form = NotificationsSettingsForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('melaoapp:notifications_config')
    else:
        form = NotificationsSettingsForm(instance=student)
    return render(request, 'melaoapp/notificationsConfigView.html', {'form': form})

@login_required(login_url='melaoapp:welcome')

melaoapp/templates/melaoapp/aboutMeConfigView.html
{% extends 'melaoapp/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Configuration" %}{% endblock %}

{% block static_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'melaoapp/css/aboutMeConfig.css' %}">
{% endblock %}

{% block static_js %}
    <script src="{% static 'melaoapp/js/languageAndThemeConfig.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="ConfigPancnel">
        <img src="{% static 'melaoapp/img/left_arrow.svg' %}" alt="Volver" class="BackButton" onclick="history.back()">
        <p class="title">{% trans "Change your profile information" %}</p>
        <form method="post" action="">
            {% csrf_token %}
            {{ form.self_description|add_class:"input-field"|attr:"placeholder:Talk about you" }}
            <button type="submit" class="button">{% trans "Update" %}</button>
        </form>
    </div>
{% endblock %}

melaoapp/templates/melaoapp/chatListView.html
{% extends 'melaoapp/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Melao - Chat{% endblock %}

{% block static_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'melaoapp/css/chatList.css' %}">
{% endblock %}

{% block static_js %}
    <script>
    let dataDummy = [
        {
            name: "Ethan Hunt",
            image: "{% static 'melaoapp/img/EthanHuntProfile.png' %}",
            last_connection: "Activo ahora"
        },
        {
            name: "Ethan Hunt",
            image: "{% static 'melaoapp/img/EthanHuntProfile.png' %}",
            last_connection: "Activo hace 2d"
        },
        {
            name: "Ethan Hunt",
            image: "{% static 'melaoapp/img/EthanHuntProfile.png' %}",
            last_connection: "Activo hace 5 min"
        },
        {
            name: "Ethan Hunt",
            image: "{% static 'melaoapp/img/EthanHuntProfile.png' %}",
            last_connection: "Activo hace 2h"
        },
        {
            name: "Ethan Hunt",
            image: "{% static 'melaoapp/img/EthanHuntProfile.png' %}",
            last_connection: "Activo hace 1 semana"
        }
        ];

        function renderPeople(people) {
            people.forEach(element => {
                const personLink = document.createElement("a");
                personLink.setAttribute("class", "person");
                // Replace '1' with a unique identifier if available in your data
                personLink.setAttribute("href", "{% url 'melaoapp:chat_view' %}");

                const personImg = document.createElement("img");
                personImg.setAttribute("src", element.image);
                personImg.setAttribute("width", "70");
                personImg.setAttribute("height", "70");
                personImg.setAttribute("alt", "X");

                const person_name = document.createElement("p");
                person_name.setAttribute("class", "person-name");
                person_name.innerText = element.name;

                const personlast_connection = document.createElement("p");
                personlast_connection.setAttribute("class", "last-connection");
                personlast_connection.innerText = element.last_connection;

                personLink.appendChild(personImg);
                personLink.appendChild(person_name);
                personLink.appendChild(personlast_connection);

                document.getElementsByClassName("chats-pannel")[0].appendChild(personLink);
            });
        }

        document.addEventListener("DOMContentLoaded", function() {
            renderPeople(dataDummy);
        });
        </script>
        {% endblock %}

{% block content %}
    <div class="chats-pannel">
    </div>
{% endblock %}

melaoapp/templates/melaoapp/modifyProfile.html
{% extends 'melaoapp/base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}Melao - Modificar Perfil{% endblock %}

{% block static_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'melaoapp/css/modifyProfile.css' %}">
{% endblock %}

{% block static_js %}
    <script src="{% static 'melaoapp/js/languageAndThemeConfig.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="pfp-button">
        {% if request.user.student.profile_picture %}
            <img id="profile-image" alt="Foto de Perfil" src="{{ request.user.student.profile_picture.url }}">
        {% else %}
            <img id="profile-image" alt="Foto de Perfil" src="{% static 'melaoapp/img/EthanHuntProfile.png' %}">
        {% endif %}

        <form method="post" action="{% url 'melaoapp:modify_profile' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% render_field form.profile_picture %}
            <button type="submit" class="button">{% trans "Update" %}</button>
        </form>
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:about_me_config_view' %}">
                <p class="title">{% trans "Personal info" %}</p>
                <p class="subtitle">{% trans "Update biography" %}</p>
            </a>
        </div>
        <a href="{% url 'melaoapp:about_me_config_view' %}">
            <img src="{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% static 'melaoapp/img/right_arrow.svg' %}{% endif %}{% endif %}" alt="">
        </a>
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:password_change' %}">
                <p class="title">{% trans "Security and Acces" %}</p>
                <p class="subtitle">{% trans "Change password" %}</p>
            </a>
        </div>
        <a href="{% url 'melaoapp:password_change' %}">
            <img src="{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% static 'melaoapp/img/right_arrow.svg' %}{% endif %}{% endif %}" alt="">
        </a>
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:language_and_theme_config_view' %}">
                <p class="title">{% trans "Appearance" %}</p>
                <p class="subtitle">{% trans "Personalize language and theme" %}</p>
            </a>
        </div>
        <a href="{% url 'melaoapp:language_and_theme_config_view' %}">
            <img src="{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% static 'melaoapp/img/right_arrow.svg' %}{% endif %}{% endif %}" alt="">
        </a>
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:privacy_config' %}">
                <p class="title">{% trans "Privacity and configuration" %}</p>
                <p class="subtitle">{% trans "Change who can see my posts" %}</p>
            </a>
        </div>
        <img src="{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% static 'melaoapp/img/right_arrow.svg' %}{% endif %}{% endif %}" alt="">
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:notifications_config' %}">
                <p class="title">{% trans "Configurate notifications" %}</p>
                <p class="subtitle">{% trans "Change notifications preferences" %}</p>
            </a>
        </div>
        <img src="{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% if request.COOKIES.theme == 'dark' %}{% static 'melaoapp/img/dark/right_arrowDark.svg' %}{% else %}{% static 'melaoapp/img/right_arrow.svg' %}{% endif %}{% endif %}" alt="">
    </div>

    <div class="option-container">
        <div class="text-container">
            <a class="black-link" href="{% url 'melaoapp:logout' %}" onclick="logout()">
                <p class="title">{% trans "Logout" %}</p>
            </a>
        </div>
    </div>
{% endblock %}

melaoapp/templates/melaoapp/password_reset_email.html
Alguien ha solicitado un restablecimiento de contraseña para su cuenta de Melao.

Si no fuiste tú, ignora este correo.

Para restablecer tu contraseña, haz clic en el siguiente enlace:
{{ protocol }}://{{ domain }}{% url 'melaoapp:password_reset_confirm' uidb64=uid token=token %}

Tu nombre de usuario es: {{ user.get_username }}

melaoapp/templates/melaoapp/searchPersonView.html
{% extends 'melaoapp/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Melao - Buscar{% endblock %}

{% block static_js %}
    <script>
        const ADD_FRIEND_URL = "{% url 'melaoapp:send-notification' %}";
        const SENDER_USERNAME = "{{ request.user.username }}";
        const CSRF_TOKEN = "{{ csrf_token }}";
    </script>
    <script src="{% static 'melaoapp/js/searchPerson.js' %}"></script>
{% endblock %}

{% block static_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'melaoapp/css/searchPeople.css' %}">
{% endblock %}

{% block content %}
    <div class="search-tab">
        <img src="{% static 'melaoapp/img/Lupa.png' %}" alt="{% trans "Search icon" %}">
        <input type="text" placeholder="{% trans "Search" %}">
        <img src="{% static 'melaoapp/img/X-Search-Icon.png' %}" alt="{% trans "Delete search icon" %}">
    </div>
    
    <div class="search-panel">
        <form method="post" id="csrf-form">{% csrf_token %}</form>
        {% for person in persons %}
        <div class="person" data-username="{{ person.user.username }}">

            {% if person.profile_picture %}
                <img src="{{ person.profile_picture.url }}" width="70" height="70" alt="X">
            {% else %}
                <img src="{% static "melaoapp/img/EthanHuntProfile.png" %}" width="70" height="70" alt="X">
            {% endif %}

            <p class="person_name">{{ person.user.first_name }} {{ person.user.last_name }}</p>
            <img src="{% if request.COOKIES.theme == 'dark' %}{% static '/melaoapp/img/dark/AddFriendDark.png'%}{% else %}{% static '/melaoapp/img/AddFriend.png'%}{% endif %}" width="30" height="30" alt="AddFriend" class="Icon Add-Friend-Button" onclick="sendFriendRequest('{{ person.user.username }}', 1)">
            <img src="{% if request.COOKIES.theme == 'dark' %}{% static '/melaoapp/img/dark/ChatDark.png'%}{% else %}{% static '/melaoapp/img/Chat.png'%}{% endif %}" width="30" height="30" alt="Chat" class="Icon">
        </div>
        {% endfor %}
    </div>
{% endblock %}

melaoapp/templates/melaoapp/welcome.html
{% extends 'melaoapp/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Welcome" %}{% endblock %}

{% block static_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'melaoapp/css/welcome.css' %}">
{% endblock %}

{% block custom_header %}
<header class="mobile-navbar">
        <p>Melao</p>
</header>
<div class="desktop-navbar">
    <ul class="nav-list">
        <li>
            <a class="logo-container" href="{% url 'melaoapp:welcome' %}">
                <img src="{% static 'melaoapp/img/logoIcono.png' %}" alt="Home">
                <p class="logo-text">Melao</p>
            </a>
        </li>
    </ul>
</div>
{% endblock %}

{% block content %}
<form method="POST" class="welcome-container">
    {% csrf_token %}

    <div class="welcome-logo">
        <img src="{% static 'melaoapp/img/logo.png' %}" alt="Logo de Melao" class="Logo" width="80" height="80">
        <h1>{% trans "Welcome to Melao" %}</h1>
    </div>
    
    <p class="description">
        {% trans "Conéctate con tus compañeros, comparte experiencias y mantente al día con lo que sucede en la comunidad ATI." %}
    </p>

    {% if form.username.errors %}
        <div class="form-error">{{ form.username.errors }}</div>
    {% endif %}
    {{ form.username|add_class:"input-field"|attr:"placeholder:Usuario"  }}

    {% if form.password.errors %}
        <div class="form-error">{{ form.password.errors }}</div>
    {% endif %}
    {{ form.password|add_class:"input-field"|attr:"placeholder:Contraseña"  }}

    <div class="remember-me">
        <label for="remember-me">{% trans "Remembre me" %}</label>
        <input type="checkbox" name="remember-me" id="remember-me">
    </div>

    <a href="{% url 'melaoapp:reset_password' %}" class="desktop-content">{% trans "Have you forgot your password?" %}</a>

    <button type="submit" class="button">
        {% trans "Login" %}
    </button>

    <button type="button" onclick="document.location.href='{% url 'melaoapp:sign_up_view' %}'" class="button sign-up">
        {% trans "Register" %}
    </button>
</form>
{% endblock %}

{% block custom_footer %}
<footer>
    <p>{% trans "Melao Project - 2025" %}</p>
</footer>
{% endblock %}